# Generated by Django 3.0.5 on 2020-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_notes_text',
            name='category',
            field=models.CharField(choices=[('subtitle', 'subtitle'), ('code', 'code'), ('content', 'content'), ('image', 'image')], default='content', max_length=20),
        ),
    ]
