# Generated by Django 3.0.5 on 2020-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
